var h = '<nav class="qqmm-nav" role="navigation">'
    + '	<div class="container">'
    + '		<div class="row">'
    + '			<div class="col-md-3 col-xs-2">'
    + '				<div id="qqmm-logo"><a href="/index.html">全生苗木</a></div>'
    + '			</div>'
    + '			<div class="col-md-6 col-xs-6 text-center menu-1">'
    + '				<ul>'
    + '					<li>'
    + '						<a href="/index.html">首页</a>'
    + '					</li>'
    + '					<li>'
    + '						<a href="/pages/about.html">关于全生</a>'
    + '					</li>'
    + '					<li>'
    + '						<a href="/pages/services.html">服务</a>'
    + '					</li>'
    + '					<li>'
    + '						<a href="/pages/contact.html">联系我们</a>'
    + '					</li>'
    + '				</ul>'
    + '			</div>'
    + '         <div class="col-md-3 col-xs-4 text-right hidden-xs menu-2">'
    + '				<ul class="qqmm-social-icons">'
    + '                 <li><i class="icon-old-phone"></i></li>'
    + '                 <li class="phone">135 0377 6641</li>'
    + '				</ul>'
    + '           </div>'
    + '		</div>'
    + '	</div>'
    + '</nav>'

document.getElementById('header').insertAdjacentHTML('afterbegin', h);